# Generated by Django 6.0.4 on 2026-04-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Accounting date of the transaction (may differ from entry date).')),
                ('description', models.TextField(help_text='Narrative description of the transaction.')),
                ('reference', models.CharField(blank=True, help_text='External reference number, e.g. invoice or receipt number.', max_length=50)),
                ('is_posted', models.BooleanField(default=False, help_text='When True, this entry has been validated and account balances updated.')),
                ('posted_at', models.DateTimeField(blank=True, help_text='Timestamp when this entry was posted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount in UZS. Set to 0 if this is a credit line.', max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount in UZS. Set to 0 if this is a debit line.', max_digits=14)),
                ('memo', models.CharField(blank=True, help_text='Optional line-level memo or note.', max_length=200)),
                ('account', models.ForeignKey(help_text='Account affected by this line.', on_delete=django.db.models.deletion.PROTECT, related_name='entry_lines', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Entry Line',
                'verbose_name_plural': 'Entry Lines',
            },
        ),
    ]
