# Generated by Django 6.0.4 on 2026-04-16 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this journal entry.', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryline',
            name='journal',
            field=models.ForeignKey(help_text='Parent journal entry.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journal.journalentry'),
        ),
    ]
