# Generated by Django 6.0.4 on 2026-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique account code, e.g. 1010, 4100.', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Human-readable account name, e.g. "Cash and Bank".', max_length=100)),
                ('account_type', models.CharField(choices=[('A', 'Asset'), ('L', 'Liability'), ('E', 'Equity'), ('R', 'Revenue'), ('X', 'Expense')], help_text='A=Asset, L=Liability, E=Equity, R=Revenue, X=Expense.', max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Running balance in UZS. Updated atomically on journal entry posting.', max_digits=14)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot receive new journal entries.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
    ]
